-- Proposed shared schema for team review. Apply ONCE after skeleton setup.
-- This additive migration preserves the skeleton CSV loading format.
BEGIN;
ALTER TABLE Users ADD COLUMN balance NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (balance >= 0);
ALTER TABLE Users ADD COLUMN address TEXT;
ALTER TABLE Products ADD CONSTRAINT products_price_nonnegative CHECK (price >= 0);

-- Sellers owner: retain inactive listings instead of deleting referenced history.
CREATE TABLE Inventory (
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL CHECK (quantity >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (seller_id, product_id)
);
-- An empty cart is represented by zero rows; no separate Carts table is needed.
CREATE TABLE CartItems (
    buyer_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (buyer_id, seller_id, product_id),
    FOREIGN KEY (seller_id, product_id) REFERENCES Inventory(seller_id, product_id)
);
CREATE TABLE Orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INT NOT NULL REFERENCES Users(id),
    placed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shipping_name TEXT NOT NULL CHECK (length(trim(shipping_name)) > 0),
    shipping_address TEXT NOT NULL CHECK (length(trim(shipping_address)) > 0)
);
CREATE TABLE OrderItems (
    order_id INT NOT NULL REFERENCES Orders(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    product_name TEXT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    fulfilled_at TIMESTAMPTZ,
    PRIMARY KEY (order_id, seller_id, product_id)
);
CREATE INDEX orders_buyer_date_idx ON Orders(buyer_id, placed_at DESC, id DESC);
CREATE INDEX orderitems_seller_order_idx ON OrderItems(seller_id, order_id);
COMMIT;
