-- Fresh skeleton development bootstrap, aligned with the team M2 report.
-- Apply ONCE, after db/create.sql and fixture loading.
-- Users/Inventory additions are development adapters, not ownership of those modules.
-- Final Users migration (password_hash, required address, is_seller) belongs to Users.
-- Existing early Carts databases: use db/migrate_carts_m2_contract.sql instead.
-- This additive migration preserves the skeleton CSV loading format.
BEGIN;
ALTER TABLE Users ADD COLUMN balance NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (balance >= 0);
ALTER TABLE Users ADD COLUMN address TEXT;
ALTER TABLE Products ADD CONSTRAINT products_price_positive CHECK (price > 0);

-- Sellers owner: current listings may be removed; carts/history survive removal.
CREATE TABLE Inventory (
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL CHECK (quantity >= 0),
    PRIMARY KEY (seller_id, product_id)
);
-- An empty cart is represented by zero rows; no separate Carts table is needed.
CREATE TABLE CartItems (
    buyer_id INT NOT NULL REFERENCES Users(id),
    seller_id INT NOT NULL REFERENCES Users(id) ON DELETE RESTRICT,
    product_id INT NOT NULL REFERENCES Products(id) ON DELETE RESTRICT,
    quantity INT NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (buyer_id, product_id, seller_id)
);
CREATE TABLE Orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INT NOT NULL REFERENCES Users(id),
    placed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    buyer_name_snapshot TEXT NOT NULL CHECK (length(trim(buyer_name_snapshot)) > 0),
    shipping_address_snapshot TEXT NOT NULL CHECK (length(trim(shipping_address_snapshot)) > 0)
);
CREATE TABLE OrderItems (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL REFERENCES Orders(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    product_name_snapshot VARCHAR(255) NOT NULL CHECK (length(trim(product_name_snapshot)) > 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
    fulfilled_at TIMESTAMPTZ,
    UNIQUE (order_id, product_id, seller_id)
);
CREATE INDEX orders_buyer_date_idx ON Orders(buyer_id, placed_at DESC, id DESC);
CREATE INDEX orderitems_seller_order_idx ON OrderItems(seller_id, order_id);
COMMIT;
