-- ONE-TIME migration from the original Carts prototype (commit 253dbec).
-- Back up the database first. This is not the fresh-install script.
-- No rows are deleted. Invalid zero-price/blank/overlong existing data causes
-- the transaction to fail and roll back; repair such data before retrying.
BEGIN;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM OrderItems WHERE length(product_name) > 255) THEN
        RAISE EXCEPTION 'Product snapshots exceed 255 characters; resolve before migration';
    END IF;
END $$;
ALTER TABLE CartItems DROP CONSTRAINT cartitems_seller_id_product_id_fkey;
ALTER TABLE CartItems ADD CONSTRAINT cartitems_seller_id_fkey
    FOREIGN KEY (seller_id) REFERENCES Users(id) ON DELETE RESTRICT;
ALTER TABLE CartItems ADD CONSTRAINT cartitems_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE RESTRICT;
ALTER TABLE CartItems DROP CONSTRAINT cartitems_pkey;
ALTER TABLE CartItems ADD PRIMARY KEY (buyer_id, product_id, seller_id);
ALTER TABLE Orders RENAME COLUMN shipping_name TO buyer_name_snapshot;
ALTER TABLE Orders RENAME COLUMN shipping_address TO shipping_address_snapshot;
ALTER TABLE OrderItems RENAME COLUMN product_name TO product_name_snapshot;
ALTER TABLE OrderItems ALTER COLUMN product_name_snapshot TYPE VARCHAR(255);
ALTER TABLE OrderItems ADD CONSTRAINT orderitems_name_nonblank
    CHECK (length(trim(product_name_snapshot)) > 0);
ALTER TABLE OrderItems DROP CONSTRAINT orderitems_pkey;
ALTER TABLE OrderItems ADD COLUMN id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE OrderItems ADD UNIQUE (order_id, product_id, seller_id);
ALTER TABLE OrderItems DROP CONSTRAINT orderitems_unit_price_check;
ALTER TABLE OrderItems ADD CONSTRAINT orderitems_unit_price_check CHECK (unit_price > 0);
ALTER TABLE Products DROP CONSTRAINT products_price_nonnegative;
ALTER TABLE Products ADD CONSTRAINT products_price_positive CHECK (price > 0);
-- Keep old availability columns as unused legacy columns to avoid deleting data.
-- Convert previously inactive listings to zero stock before ignoring active.
UPDATE Inventory SET quantity = 0 WHERE active = FALSE;
COMMIT;
